"""Initial schema

Revision ID: 09d933cd9aaf
Revises: 
Create Date: 2026-03-22 19:40:39.835737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d933cd9aaf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_introduction',
    sa.Column('part_introduction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('auxiliary_texts', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('part_introduction_id')
    )
    op.create_table('test_available',
    sa.Column('available_test_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('available_test_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('answer_sheet',
    sa.Column('answer_sheet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('answer_sheet_id')
    )
    op.create_table('part',
    sa.Column('part_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=True),
    sa.Column('part_name', sa.String(length=255), nullable=True),
    sa.Column('text_question_content', sa.Text(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('questions_type', sa.String(length=255), nullable=True),
    sa.Column('introduction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['introduction_id'], ['part_introduction.part_introduction_id'], ),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_table('option_answer',
    sa.Column('option_answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer_sheet_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.String(length=255), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheet.answer_sheet_id'], ),
    sa.PrimaryKeyConstraint('option_answer_id')
    )
    op.create_table('section',
    sa.Column('section_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('section_number', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('section_audio_link', sa.String(length=2000), nullable=True),
    sa.Column('section_image_link', sa.String(length=2000), nullable=True),
    sa.Column('section_video_link', sa.String(length=2000), nullable=True),
    sa.Column('text_question_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['part.part_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('test_area',
    sa.Column('test_area_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('available_test_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.Enum('LISTENING', 'READING', 'WRITING', 'SPEAKING', name='areatest'), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['available_test_id'], ['test_available.available_test_id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.part_id'], ),
    sa.PrimaryKeyConstraint('test_area_id')
    )
    op.create_table('test_result',
    sa.Column('test_result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listening_corrects', sa.Integer(), nullable=True),
    sa.Column('listening_max', sa.Float(), nullable=True),
    sa.Column('reading_corrects', sa.Integer(), nullable=True),
    sa.Column('reading_max', sa.Float(), nullable=True),
    sa.Column('writing_min', sa.Float(), nullable=True),
    sa.Column('writing_max', sa.Float(), nullable=True),
    sa.Column('speaking_min', sa.Float(), nullable=True),
    sa.Column('speaking_max', sa.Float(), nullable=True),
    sa.Column('clb_min', sa.Float(), nullable=True),
    sa.Column('clb_max', sa.Float(), nullable=True),
    sa.Column('clb_average', sa.Float(), nullable=True),
    sa.Column('result_date', sa.DateTime(), nullable=True),
    sa.Column('available_test_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer_sheet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheet.answer_sheet_id'], ),
    sa.ForeignKeyConstraint(['available_test_id'], ['test_available.available_test_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('test_result_id')
    )
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('audio_link', sa.String(length=2000), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.section_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('question_option',
    sa.Column('option_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_option')
    op.drop_table('question')
    op.drop_table('test_result')
    op.drop_table('test_area')
    op.drop_table('section')
    op.drop_table('option_answer')
    op.drop_table('part')
    op.drop_table('answer_sheet')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('test_available')
    op.drop_table('part_introduction')
    # ### end Alembic commands ###
