"""add_admin_authorization_fields

Revision ID: 16e977332b0b
Revises: 09d933cd9aaf
Create Date: 2026-03-26 19:28:25.772758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e977332b0b'
down_revision: Union[str, None] = '09d933cd9aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_authorized', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('authorized_by_admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['authorized_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'authorized_by_admin_id')
    op.drop_column('users', 'authorized_at')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_authorized')
    # ### end Alembic commands ###
