"""Add start and end time to answer sheet

Revision ID: 63748d876fd0
Revises: 29fc5f5c1365
Create Date: 2026-04-06 15:55:29.247048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63748d876fd0'
down_revision: Union[str, None] = '29fc5f5c1365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_sheet', sa.Column('start_time', sa.String(length=255), nullable=True))
    op.add_column('answer_sheet', sa.Column('end_time', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_sheet', 'end_time')
    op.drop_column('answer_sheet', 'start_time')
    # ### end Alembic commands ###
